---
# --------------------------------------------------------------------------
# Template input file to define local variable settings for use with
# an OpenHPC installation.
# --------------------------------------------------------------------------

#
#escape definitions
#
# escape for ':'
d_colon: ':'

#
#Node types
#
# All nodes
nt_allnodes: 'all' 
#SMS(master node)
nt_sms: 'sms'
#Computing nodes
nt_cnodes: 'cnodes'
#I/O (Lustre server/BeegFS server)
nt_ionodes: 'ionodes'
#Development environment
nt_devnodes: 'devnodes'


# Release package 
ohpc_release_rpm_intel: "http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm"
ohpc_release_rpm_arm: "http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/aarch64/ohpc-release-1.3-1.el7.aarch64.rpm"

# SMS (master) node settings
sms_name: "sms"

# Local (internal) IP address on SMS
sms_ip: "192.168.44.11"

# Internal ethernet interface on SMS
sms_eth_internal: "eth2"

# Subnet network for internal cluster network
internal_network: "192.168.44.0"

# Subnet netmask for internal cluster network
internal_netmask: "255.255.255.0"

# Subnet broadcast for internal cluster network
internal_broadcast: "192.168.44.255"

# Gateway for internal cluster network
internal_gateway: "192.168.44.11"

# internal domain name for internal cluster network
internal_domain_name: "linaro.org"

# internal domain name server for internal cluster network
internal_domain_name_servers: "192.168.44.11"

# Local domainname for cluster (xCAT recipe only)
domain_name: "local"

# Path to copy of OS ISO image (xCAT recipe only)
iso_path: "-" 

# Provisioning interface used by compute hosts (Warewulf recipe only)
eth_provision: "eth2"

# ethernet interface on computing nodes( for non-warewulf environment )
cnode_eth_internal: "eth2"

# Flags for optional installation/configuration
enable_beegfs_client: false
enable_mpi_defaults: true
enable_mpi_opa: false
enable_clustershell: true
enable_ipmisol: false
enable_opensm: false
enable_ipoib: false
enable_ganglia: true
enable_genders: true
enable_kargs: false
enable_lustre_client: false
enable_mrsh: true
enable_nagios: true
enable_powerman: false
enable_intel_packages: false
enable_dhcpd_server: false
enable_ifup: false
enable_warewulf: true
enable_nfs_ohpc: false
enable_nfs_home: true

#
#dhcpd settings
#
# default lease time for internal cluster network
internal_default_lease_time: "21600"
# max lease time for internal cluster network
internal_max_lease_time: "43200"

#
# compute node settings
#
# total number of computes
num_computes: 2

# regex and starting prefix that matches defined compute hostnames
compute_regex: "c*"
compute_prefix: "c"

compute_nodes:
- { num: 1, c_name: "c1", c_ip: "192.168.44.21", c_mac: "52:54:00:44:00:01", c_bmc: "192.168.66.11"}
- { num: 2, c_name: "c2", c_ip: "192.168.44.22", c_mac: "52:54:00:44:00:02", c_bmc: "192.168.66.12"}


# Optional settings
#
# IPoIB addresses for computes
compute_ipoib:
- { num: 1, c_ipoib: "192.168.55.21", c_cid: "ff:00:00:00:00:00:02:00:00:02:c9:00:50:80:02:00:00:55:00:01"}
- { num: 2, c_ipoib: "192.168.55.22", c_cid: "ff:00:00:00:00:00:02:00:00:02:c9:00:50:80:02:00:00:55:00:02"}

# BeeGFS repository URL
beegfs_repo: "https://www.beegfs.io/release/beegfs_6/dists/beegfs-rhel7.repo"

# BeeGFS sysMgmtdHost
sysmgmtd_host: "192.168.55.254"

